# imports
from turtle import *


def draw_art():
    bgcolor("gray")
    speed(1)
    color('yellow')
    begin_fill()
    forward(135)
    end_fill()
    circle(0, 90)
    begin_fill()
    color('blue')
    forward(135)
    circle(0, 90)
    forward(135)
    end_fill()
    begin_fill()
    color('magenta')
    circle(0, 90)
    forward(135)
    circle(0, 270)
    begin_fill()
    forward(135)
    color('pink')
    circle(0, 270)
    forward(135)
    end_fill()
    circle(0, 270)
    forward(135)
    circle(0, 90)
    forward(135)
    circle(0, 90)
    begin_fill()
    color('orange')
    forward(135)
    circle(0, 90)
    forward(135)
    end_fill()
    done()


draw_art()
